package com.abelhzo.client.bus.roles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-27T22:52:13.510-05:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "RolesServiceSOAP", 
                  wsdlLocation = "http://localhost:8085/UsersManagementSOAP/RolesServiceSOAP?wsdl",
                  targetNamespace = "http://abelhzo.roles/") 
public class RolesServiceSOAP_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://abelhzo.roles/", "RolesServiceSOAP");
    public final static QName RolesServicePortSOAP = new QName("http://abelhzo.roles/", "RolesServicePortSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/UsersManagementSOAP/RolesServiceSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RolesServiceSOAP_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/UsersManagementSOAP/RolesServiceSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RolesServiceSOAP_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RolesServiceSOAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RolesServiceSOAP_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RolesServiceSOAP_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RolesServiceSOAP_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RolesServiceSOAP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RolesServiceSOAP
     */
    @WebEndpoint(name = "RolesServicePortSOAP")
    public RolesServiceSOAP getRolesServicePortSOAP() {
        return super.getPort(RolesServicePortSOAP, RolesServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RolesServiceSOAP
     */
    @WebEndpoint(name = "RolesServicePortSOAP")
    public RolesServiceSOAP getRolesServicePortSOAP(WebServiceFeature... features) {
        return super.getPort(RolesServicePortSOAP, RolesServiceSOAP.class, features);
    }

}
